### ISSUE TITLE
Change in podManagementPolicy (#124) introduces breaking changes for existing deployments

### ISSUE THREAD

**Issue by sebastianmarkow** [qdrant/qdrant-helm#139]
`podManagementPolicy: Parallel` is immutable for statefulsets. Given a present installation of qdrant, an upgrade is a non-trivial task without downtime. 

https://github.com/qdrant/qdrant-helm/blob/257e47a75e567e0b7dce7f6afbefebf41b0358f8/charts/qdrant/templates/statefulset.yaml#L12

Is this intended with #124, as it was not mentioned as a breaking change in the release notes of v0.7.5?

**Comment by viktordanov** [comment]
Ran into the same. This is the second undocumented breaking change I've ran into with this helm repo.
