### ISSUE TITLE
Add support for enabling ShareProcessNamespace

### ISSUE THREAD

**Issue by chris-kapstan** [qdrant/qdrant-helm#162]
Hi, I would like to run a sidecar that can communicate with the Qdrant container on the same pod. I believe this should be a simple change, just need to allow enabling the `shareProcessNamespace` field on the statefulset's pod template https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#podspec-v1-core https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/

Happy to raise a PR for this issue if required

**Comment by SamirPS** [comment]
Hello,

Can you tell me more about your use case ?

**Comment by chris-kapstan** [comment]
Sure, essentially I want to run Qdrant in a cluster and have automated snapshots taken and uploaded to remote storage. One way I could do this would be to run a script that connects to each pod and uses `kubectl cp` to transfer data out but this seemed clunky. By having a sidecar run alongside the container I could containerize my snapshot script and have snapshots uploaded with labels to indicate the pod's identity

**Comment by SamirPS** [comment]
Hello,

Sure we can add your request as long as this setting is optional. Do you have time to do the PR?
