### ISSUE TITLE
restore from snapshot

### ISSUE THREAD

**Issue by kyue1005** [qdrant/qdrant-helm#17]
The documentation stated that `Restoring snapshots is done through the Qdrant CLI at startup time.`

So it seems there is no way to restore from snapshots while using Helm chart right now, a simple way would allow adding start-up flag in `initialize.sh` script.

**Comment by M-Nawar** [comment]
Hi  @kyue1005, thanks a lot for your feedback! We're already discussing how to best support this. Could you tell us more about your setup? 

- is it a single/multi node cluster
- are you using a cloud provider/self provisioned Kubernetes
- where do you store the backup

**Comment by kyue1005** [comment]
- is it a single/multi node cluster -> single node atm, plan to use multi node when replication is available
- are you using a cloud provider/self provisioned Kubernetes -> we are using EKS
- where do you store the backup -> we are planning to use Object storage, e.g. S3
