### ISSUE TITLE
Hardcoded p2p port in configmap template

### ISSUE THREAD

**Issue by mortum5** [qdrant/qdrant-helm#216]
If I understand correctly, changing the p2p port via value.yaml is permitted behavior. But at the same time, the initialization script rigidly fixes the port through which the nodes will communicate with each other in [configmap.yaml](https://github.com/qdrant/qdrant-helm/blob/0d78af2b99f0a15c02ee75ae74bd5e5e8c94058b/charts/qdrant/templates/configmap.yaml#L13)

**Comment by NathanSavageKaimai** [comment]
I have made a pr for this and another clustering issue to do with tls. Hopefully it should be fairly qrick to review and merge. :)
