### ISSUE TITLE
ServieMonitor should use with higher precedence the readOnlyApiKey

### ISSUE THREAD

**Issue by vitali-ipquants** [qdrant/qdrant-helm#219]
Hello Qdrant team,

If in the values.yaml are defined both apiKey and readOnlyApiKey 
it will be better if the ServiceMonitor refers to the read-only key.
The Prometheus will be able to collect metrics with the read-only key,
so there's no need to pass it the more powerful key.
 
Thank you

**Comment by arthurk** [comment]
Good catch! I've create a PR for it here https://github.com/qdrant/qdrant-helm/pull/221
