### ISSUE TITLE
Chart Releases

### ISSUE THREAD

**Issue by alextriquet** [qdrant/qdrant-helm#26]
Hello,
We are using this chart in production with fluxCD.
The lack of releases / tags is a concern to install Qdrant through the Helm Repository since we are not able to track which version of the chart we are pulling. Going through the main branch of the GitRepository is a possibility but it entails the same lack of control on our part ; since it is not versionned we are not protected from breaking changes.
Would it be possible to add release / tags ?
I can provide help if needed 😃

**Comment by fabriziobonavita** [comment]
Hi @alextriquet,

thank you for your feedback!
I absolutely understand the need for releases, will make a ticket and we'll take care of it.

**Comment by fabriziobonavita** [comment]
@alextriquet, just to clarify, there are already releases as you can see [here](https://github.com/qdrant/qdrant-helm/tree/gh-pages), but we did not tag on release yet. 
We will add that and thank you for reporting!

**Comment by M-Nawar** [comment]
Thank you, added tags for releases!
