### ISSUE TITLE
Allow volume expansion directly by Helm

### ISSUE THREAD

**Issue by danielbichuetti** [qdrant/qdrant-helm#34]
Today, if we try to increase the storage size, it will fail with the following message:

` Helm Release qdrant/qdrant-9ba92ff7: cannot patch "qdrant-9ba92ff7" with kind StatefulSet: StatefulSet.apps "qdrant-9ba92ff7" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden`

Would it be possible to change how volumes are handled to allow volume expansion in a current running cluster via Helm?

PS: I know that because of the STS usage, this is complicated and probably this would be better accomplished if using an operator pod.

**Comment by M-Nawar** [comment]
Hi @danielbichuetti thanks for your feedback, potentially we could create pvcs using a yaml file according to the number of replicas and mount them directly, then editing the pvc yaml files to increase storage size. However I'll need to double check the behaviour  incase of replicas scaleup, that it creates new pvcs for the new replicas.
For now to scale up the storage size you'd need to edit the PVC directly in kubernetes and increase the size, this would solve the sizing issue, if you want the statefulset to show the new size, you'd have to delete and recreate the statefulset.
Something like:
kubectl edit pvc PVC_NAME (to increase size)
kubectl get sts STS_NAME -o yaml > STS_NAME.yaml (save old sts yaml)
edit the STS_NAME.yaml and adjust the storage size
kubectl delete sts STS_NAME 
kubectl apply -f STS_NAME.yaml

Incase of deleting and recreating STS Make sure that PersistentVolumeClaim retention policy 
 is retain and not delete, so the PVCs are not deleted.

**Comment by wodka** [comment]
I really hope that https://github.com/kubernetes/enhancements/pull/3412 will get through at some point to allow this on the config level without having to do multiple commands

**Comment by mac-chaffee** [comment]
Yeah until StatefulSets directly support resizing, the procedure you have to follow is this one: https://dev.to/ishuar/expanding-persistent-volume-for-statefulsets-in-kubernetes-4886
