### ISSUE TITLE
Use `/readyz` and `/livez` endpoints

### ISSUE THREAD

**Issue by timvisee** [qdrant/qdrant-helm#71]
<https://github.com/qdrant/qdrant/pull/2409> has implemented `/livez` and `/readyz` endpoints for health checking. This will be part of the next Qdrant release (1.5.0).

I think we should incorporate those in our Helm Chart rather than relying `/`. `/livez` and `/readyz` do also properly work if the user has an API key configured.

**Comment by timvisee** [comment]
These endpoints are now released as part of [`v1.5.0`](https://github.com/qdrant/qdrant/releases/tag/v1.5.0).

The documentation PR on it can be found here: https://github.com/qdrant/landing_page/pull/280

**Comment by bashofmann** [comment]
Thanks, I'll work on this this afternoon.

**Comment by timvisee** [comment]
Thank you for picking this up so quickly!
