### ISSUE TITLE
WARN qdrant::startup: Failed to create init file indicator: Read-only file system (os error 30)

### ISSUE THREAD

**Issue by tekumara** [qdrant/qdrant-helm#74]
On startup when using version 0.5.0 of the charts I see:
```
$ kubectl logs -l "app.kubernetes.io/name=qdrant,app.kubernetes.io/instance=qdrant" -f --tail=-1
...
WARN qdrant::startup: Failed to create init file indicator: Read-only file system (os error 30)
```

**Comment by bashofmann** [comment]
Is this a fresh installation or  did you upgrade from a previous version? If you upgraded, from which version? What are your helm values?

**Comment by tekumara** [comment]
Thanks for looking into this! It's a fresh install  .. here's my [values file](https://github.com/tekumara/qdrant-demo/blob/19c71c4/infra/values.yaml)
