### ISSUE TITLE
Make annotations for the ServiceAccount configurable

### ISSUE THREAD

**Issue by oliviermichaelis** [qdrant/qdrant-helm#89]
Thanks for maintaining the helm-chart!

In my use-case, the `ServiceAccount` has to assume another identity, in my case an AWS Identity and Access Management (IAM) role. Unfortunately, the helm chart currently does not allow any customization of the `ServiceAccount`. For EKS, I would have to provide a `eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role` `annotation` for the `ServiceAccount` to assume that role.

Would it be possible to either
* add support for custom `annotations` on the `ServiceAccount`
* or support providing an external `ServiceAccount` name, e.g. with a `existingServiceAccountName` configuration key? :)

**Comment by bashofmann** [comment]
Thanks. We will add support for custom annotations for the ServiceAccount.

**Comment by oliviermichaelis** [comment]
Thank you @bashofmann!
