### ISSUE TITLE
Setting storage capacity not working

### ISSUE THREAD

**Issue by mclacore** [qdrant/qdrant-helm#99]
I have deployed the Qdrant helm chart. And I'm trying to update the storage capacity using the `values.yaml`, but any change I make doesn't impact the pods or pvc

**Comment by bashofmann** [comment]
This is a limitation of the Kubernetes StatefulSet controller.

One way to do this as mentioned in this article: https://serverfault.com/questions/955293/how-to-increase-disk-size-in-a-stateful-set,

Delete the StatefulSet while keeping the Pods running
```
kubectl delete statefulset --cascade=orphan qdrant
```

Edit the PVC size to the desired larger size, e.g. to 20Gi
```
kubectl edit pvc qdrant-storage-qdrant-0
```

Reinstall the Helm chart with the recreate-pods Flag. This will restart the Pods and during restart the PVCs will be expanded
```
helm upgrade --install qdrant qdrant/qdrant --set persistence.size=20Gi --recreate-pods
```

Note that your StorageClass must allow volume expansion.
